spring:
  application:
    name: tripmate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

server:
  servlet:
    context-path: /planner
  port: 8080

logging:
  config: classpath:log4j2.xml

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
