spring:
  application:
    name: tripmate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small
    anthropic:
      chat:
        options:
          model: claude-haiku-4-5
          temperature: 0.3
          max-tokens: 4000
    deepseek:
      chat:
        options:
          model: deepseek-chat
          temperature: 0.3
    mcp:
      client:
        enabled: true
        name: tripmate-mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 30s
        sse:
          connections:
            airbnb-mcp-server:
              url: http://localhost:8090
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

server:
  servlet:
    context-path: /planner
  port: 8080

logging:
  config: classpath:log4j2.xml

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'

rag:
  topK: 5
  similarity-threshold: 0.1
  delete-previous-related-embeddings: false

weather:
  visualcrossing:
    url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
    apiKey: ${VISUALCROSSING_API_KEY:}

flight:
  aviationstack:
    url-root: https://api.aviationstack.com/v1
    url-airports: ${flight.aviationstack.url-root}/airports
    url-flights: ${flight.aviationstack.url-root}/flights
    access-key: ${AVIATIONSTACK_ACCESS_KEY:}

currency-exchange:
  vat-comply:
    url: https://api.vatcomply.com/rates

tripmate:
  mcp:
    retry:
      max-attempts: 3
      backoff-millis: 2000
